"""Install the SAP AI Core model-provider drop-in for Hermes."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

PLUGIN_INIT = '''"""SAP AI Core model provider for Hermes Agent."""

from hermes_sap_aicore.provider import register

register()
'''

PLUGIN_YAML = """name: sap-aicore
kind: model-provider
version: 0.1.0
description: SAP AI Core Generative AI Hub via local OpenAI-compatible proxy
author: Soeren Leibach
requires_env:
  - name: SAP_AICORE_PROXY_KEY
    description: Local proxy key sent by Hermes. The proxy binds to localhost and does not forward this value to SAP.
    secret: true
"""

PLUGIN_README = """# SAP AI Core Hermes Provider

This drop-in provider is generated by `hermes-sap-aicore-install`.

Run the proxy before using Hermes:

```bash
sap-aicore-hermes-proxy
```

Then use Hermes with:

```bash
hermes -z "Say hello" --provider sap-aicore -m <SAP_AI_CORE_DEPLOYMENT_ID>
```
"""


def _hermes_home() -> Path:
    try:
        from hermes_constants import get_hermes_home

        return get_hermes_home()
    except Exception:
        return Path(os.getenv("HERMES_HOME", "~/.hermes")).expanduser()


def _append_env(env_path: Path, values: dict[str, str]) -> None:
    existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    lines = []
    for key, value in values.items():
        if not value or f"{key}=" in existing:
            continue
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    if not lines:
        return
    env_path.parent.mkdir(parents=True, exist_ok=True)
    prefix = "" if not existing or existing.endswith("\n") else "\n"
    env_path.write_text(existing + prefix + "\n".join(lines) + "\n", encoding="utf-8")


def configure_config_yaml(
    config_path: Path,
    *,
    proxy_url: str,
    key_env: str = "SAP_AICORE_PROXY_KEY",
    display_name: str = "SAP AI Core",
) -> bool:
    """Register ``sap-aicore`` under ``providers:`` so the /model picker can switch to it.

    The interactive ``/model`` switch resolves providers through
    ``hermes_cli/providers.py`` (models.dev + config.yaml ``providers:``), which is
    independent of the plugin registry. Without this entry the picker lists the
    provider but switching fails with "Unknown provider 'sap-aicore'".

    Returns True when the file was written.
    """
    try:
        import yaml
    except Exception:
        return False

    data: dict = {}
    if config_path.exists():
        try:
            loaded = yaml.safe_load(config_path.read_text(encoding="utf-8"))
            data = loaded if isinstance(loaded, dict) else {}
        except Exception:
            return False

    providers = data.get("providers")
    if not isinstance(providers, dict):
        providers = {}
    providers["sap-aicore"] = {
        "name": display_name,
        "base_url": proxy_url,
        "key_env": key_env,
        "transport": "openai_chat",
    }
    data["providers"] = providers

    model = data.get("model")
    if isinstance(model, dict) and str(model.get("provider") or "").strip().lower() == "sap-aicore":
        # Hermes may keep a stale model-level base_url from the previously
        # active provider. Runtime resolution prefers that value over the
        # providers.sap-aicore entry, so correct it when SAP AI Core is active.
        model["base_url"] = proxy_url

    if config_path.exists():
        backup = config_path.with_name(config_path.name + ".bak")
        backup.write_text(config_path.read_text(encoding="utf-8"), encoding="utf-8")

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        yaml.safe_dump(data, sort_keys=False, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )
    return True


def install(
    hermes_home: Path,
    *,
    write_env: bool,
    env_values: dict[str, str],
    write_config: bool = False,
    proxy_url: str = "http://127.0.0.1:8765/v1",
    key_env: str = "SAP_AICORE_PROXY_KEY",
) -> Path:
    provider_dir = hermes_home / "plugins" / "model-providers" / "sap-aicore"
    provider_dir.mkdir(parents=True, exist_ok=True)
    (provider_dir / "__init__.py").write_text(PLUGIN_INIT, encoding="utf-8")
    (provider_dir / "plugin.yaml").write_text(PLUGIN_YAML, encoding="utf-8")
    (provider_dir / "README.md").write_text(PLUGIN_README, encoding="utf-8")

    if write_env:
        _append_env(hermes_home / ".env", env_values)

    if write_config:
        configure_config_yaml(hermes_home / "config.yaml", proxy_url=proxy_url, key_env=key_env)

    return provider_dir


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Install the SAP AI Core provider plugin into HERMES_HOME.")
    parser.add_argument("--hermes-home", type=Path, default=_hermes_home())
    parser.add_argument("--service-key", help="Path to SAP AI Core service-key JSON.")
    parser.add_argument("--deployment-id", help="Default SAP AI Core deployment id.")
    parser.add_argument("--model-name", help="Default foundation model name for orchestration mode, e.g. anthropic--claude-4.5-sonnet.")
    parser.add_argument(
        "--models",
        help="Optional comma-separated list to pin the model picker. Omit to list all live AI Core models.",
    )
    parser.add_argument("--api-mode", choices=("foundation", "orchestration"), default="orchestration")
    parser.add_argument("--resource-group", default="default", help="SAP AI Core resource group.")
    parser.add_argument("--proxy-url", default="http://127.0.0.1:8765/v1")
    parser.add_argument("--proxy-key", default="local-sap-aicore")
    parser.add_argument("--write-env", action="store_true", help="Append non-existing values to HERMES_HOME/.env.")
    parser.add_argument(
        "--write-config",
        action="store_true",
        help="Register sap-aicore in HERMES_HOME/config.yaml so the /model picker can switch to it.",
    )
    args = parser.parse_args(argv)

    env_values = {
        "SAP_AICORE_SERVICE_KEY": args.service_key or "",
        "SAP_AICORE_DEPLOYMENT_ID": args.deployment_id or "",
        "SAP_AICORE_MODEL_NAME": args.model_name or "",
        # Leave SAP_AICORE_MODELS empty unless explicitly pinned, so the proxy
        # lists every live AI Core model in the picker.
        "SAP_AICORE_MODELS": args.models or "",
        "SAP_AICORE_API_MODE": args.api_mode or "",
        "SAP_AICORE_RESOURCE_GROUP": args.resource_group or "",
        "SAP_AICORE_PROXY_BASE_URL": args.proxy_url or "",
        "SAP_AICORE_PROXY_KEY": args.proxy_key or "",
    }
    # config.yaml registration is what makes the interactive /model switch work,
    # so enable it whenever the user is doing the env-writing setup pass.
    write_config = args.write_config or args.write_env
    provider_dir = install(
        args.hermes_home.expanduser(),
        write_env=args.write_env,
        env_values=env_values,
        write_config=write_config,
        proxy_url=args.proxy_url or "http://127.0.0.1:8765/v1",
        key_env="SAP_AICORE_PROXY_KEY",
    )
    print(f"Installed SAP AI Core Hermes provider: {provider_dir}")
    if args.write_env:
        print(f"Updated environment file: {args.hermes_home.expanduser() / '.env'}")
    if write_config:
        print(f"Registered provider in: {args.hermes_home.expanduser() / 'config.yaml'}")
    if not args.write_env:
        print("Set SAP_AICORE_SERVICE_KEY, SAP_AICORE_DEPLOYMENT_ID, and SAP_AICORE_PROXY_KEY before running Hermes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
